### ISSUE TITLE
Mixlib-lib gem out of date

### ISSUE THREAD

**Issue by arkpoah** [sensu-plugins/sensu-plugins-sftp#21]
Hello,

I get an error when check is ran via bonsai asset

```
Check failed to run: can't modify frozen String, ["/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:315:in `build_option_arguments'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:269:in `block (2 levels) in opt_parser'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:268:in `each'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:268:in `block in opt_parser'", "/var/cache/sensu/sensu-agent/a28952fd93fc63db1f8988c7bc40b0ad815eb9f35ef7317d6caf5d77ecfbfd824a9db54184400aa0c81c29b34cb48c7e8c6e3f17891aaf84cafa3c134266a61a/lib/ruby/2.4.0/optparse.rb:1062:in `initialize'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:263:in `new'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:263:in `opt_parser'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:230:in `parse_options'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:16:in `initialize'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:58:in `new'", "/var/cache/sensu/sensu-agent/a4b1117e6bd459e524db1e706d83930e6f7f69ee53de35b9c4a8a07c655d13bfbbc203fd8efb53501d91ae4ff044e3cf86f7d37f31928322155ab285bca8ac54/lib/ruby/2.4.0/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

It seems the asset is getting a very old version of mixlib-cli.

**Comment by arkpoah** [comment]
can you also update bonsai plz ?

**Comment by nixwiz** [comment]
Done.  Sorry about that.
